# ============================================================
# ALERTA UTEC - SERVERLESS COMPOSE
# ============================================================

org: ${env:ORG_NAME}
app: alerta-utec-backend
stage: dev

services:
  # Capa compartida con dependencias Python
  dependencias:
    path: Dependencias
    hooks:
      # Hook para crear tablas y poblar datos después de desplegar dependencias
      after:deploy:finalize: |
        echo "📊 Creando infraestructura y poblando datos..."
        cd DataGenerator
        python3 DataPoblator.py

  # Microservicio de gestión de usuarios
  usuarios:
    path: Usuarios
    dependsOn:
      - dependencias

  # Microservicio de gestión de incidentes
  incidentes:
    path: Incidentes
    dependsOn:
      - dependencias
      - usuarios

  # Microservicio de analítica
  analitica:
    path: Analitica
    dependsOn:
      - dependencias
      - incidentes

